// generated by stringer -type=MsgType; DO NOT EDIT

package irc

import "fmt"

const (
	_MsgType_name_0 = "PRIVMSGNOTICENICKJOINPARTQUITTOPICKICKMODEPINGPONG"
	_MsgType_name_1 = "RPL_NOTOPICRPL_TOPIC"
	_MsgType_name_2 = "RPL_NAMREPLY"
)

var (
	_MsgType_index_0 = [...]uint8{0, 7, 13, 17, 21, 25, 29, 34, 38, 42, 46, 50}
	_MsgType_index_1 = [...]uint8{0, 11, 20}
	_MsgType_index_2 = [...]uint8{0, 12}
)

func (i MsgType) String() string {
	switch {
	case 1 <= i && i <= 11:
		i -= 1
		return _MsgType_name_0[_MsgType_index_0[i]:_MsgType_index_0[i+1]]
	case 331 <= i && i <= 332:
		i -= 331
		return _MsgType_name_1[_MsgType_index_1[i]:_MsgType_index_1[i+1]]
	case i == 353:
		return _MsgType_name_2
	default:
		return fmt.Sprintf("MsgType(%d)", i)
	}
}
